### ISSUE TITLE
Fix dependency injection

### ISSUE THREAD

**Issue by lrottach** [lrottach/az-reaper#38]
Currently, signaling an entity fails with the following errors. As soon as constructor is removed, the signaling process is working again.

**Error:**
```
[2024-05-29T15:42:38.774Z] Function 'EventGridTrigger', Invocation id 'a41ceb7a-bdc9-4b32-a89f-a1b2be6b6881': An exception was thrown by the invocation.
[2024-05-29T15:42:38.774Z] Result: Function 'EventGridTrigger', Invocation id 'a41ceb7a-bdc9-4b32-a89f-a1b2be6b6881': An exception was thrown by the invocation.
[2024-05-29T15:42:38.774Z] Exception: System.InvalidOperationException: Each parameter in the deserialization constructor on type 'AzureReaper.Entities.AzureResourceEntity' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.
[2024-05-29T15:42:38.774Z]    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
[2024-05-29T15:42:38.774Z]    at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-05-29T15:42:38.774Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-05-29T15:42:38.774Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-05-29T15:42:38.774Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
[2024-05-29T15:42:38.774Z]    at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
[2024-05-29T15:42:38.774Z]    at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
[2024-05-29T15:42:38.774Z]    at Azure.Core.Serialization.JsonObjectSerializer.Deserialize(Stream stream, Type returnType, CancellationToken cancellationToken)
[2024-05-29T15:42:38.774Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.ObjectConverterShim.Deserialize(String data, Type targetType) in /_/src/Worker.Extensions.DurableTask/ObjectConverterShim.cs:line 32
[2024-05-29T15:42:38.774Z]    at Microsoft.DurableTask.DataConverter.Deserialize[T](String data)
[2024-05-29T15:42:38.774Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.ToEntityMetadata[T](EntityMetadata metadata, Boolean includeState)
[2024-05-29T15:42:38.774Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.<GetEntityAsync>b__6_0[TState](EntityMetadata e, Boolean s)
[2024-05-29T15:42:38.774Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.GetEntityCoreAsync[TMetadata](EntityInstanceId id, Boolean includeState, Func`3 select, CancellationToken cancellation)
[2024-05-29T15:42:38.774Z]    at AzureReaper.EventGridTrigger.Run(EventGridEvent eventGridEvent, DurableTaskClient client) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/EventGridTrigger.cs:line 36
[2024-05-29T15:42:38.774Z]    at AzureReaper.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 43
[2024-05-29T15:42:38.775Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-05-29T15:42:38.775Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-05-29T15:42:38.775Z] Stack:    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
[2024-05-29T15:42:38.775Z]    at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-05-29T15:42:38.775Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-05-29T15:42:38.775Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-05-29T15:42:38.775Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
[2024-05-29T15:42:38.775Z]    at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
[2024-05-29T15:42:38.775Z]    at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
[2024-05-29T15:42:38.775Z]    at Azure.Core.Serialization.JsonObjectSerializer.Deserialize(Stream stream, Type returnType, CancellationToken cancellationToken)
[2024-05-29T15:42:38.775Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.ObjectConverterShim.Deserialize(String data, Type targetType) in /_/src/Worker.Extensions.DurableTask/ObjectConverterShim.cs:line 32
[2024-05-29T15:42:38.775Z]    at Microsoft.DurableTask.DataConverter.Deserialize[T](String data)
[2024-05-29T15:42:38.775Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.ToEntityMetadata[T](EntityMetadata metadata, Boolean includeState)
[2024-05-29T15:42:38.775Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.<GetEntityAsync>b__6_0[TState](EntityMetadata e, Boolean s)
[2024-05-29T15:42:38.775Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.GetEntityCoreAsync[TMetadata](EntityInstanceId id, Boolean includeState, Func`3 select, CancellationToken cancellation)
[2024-05-29T15:42:38.775Z]    at AzureReaper.EventGridTrigger.Run(EventGridEvent eventGridEvent, DurableTaskClient client) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/EventGridTrigger.cs:line 36
[2024-05-29T15:42:38.775Z]    at AzureReaper.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 43
[2024-05-29T15:42:38.775Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-05-29T15:42:38.775Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89.
[2024-05-29T15:42:38.805Z] Executed 'Functions.EventGridTrigger' (Failed, Id=a41ceb7a-bdc9-4b32-a89f-a1b2be6b6881, Duration=260ms)
[2024-05-29T15:42:38.805Z] System.Private.CoreLib: Exception while executing function: Functions.EventGridTrigger. System.Private.CoreLib: Result: Failure
[2024-05-29T15:42:38.805Z] Exception: System.InvalidOperationException: Each parameter in the deserialization constructor on type 'AzureReaper.Entities.AzureResourceEntity' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive.
[2024-05-29T15:42:38.805Z]    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
[2024-05-29T15:42:38.805Z]    at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-05-29T15:42:38.805Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-05-29T15:42:38.805Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-05-29T15:42:38.805Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
[2024-05-29T15:42:38.805Z]    at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
[2024-05-29T15:42:38.805Z]    at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
[2024-05-29T15:42:38.805Z]    at Azure.Core.Serialization.JsonObjectSerializer.Deserialize(Stream stream, Type returnType, CancellationToken cancellationToken)
[2024-05-29T15:42:38.805Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.ObjectConverterShim.Deserialize(String data, Type targetType) in /_/src/Worker.Extensions.DurableTask/ObjectConverterShim.cs:line 32
[2024-05-29T15:42:38.805Z]    at Microsoft.DurableTask.DataConverter.Deserialize[T](String data)
[2024-05-29T15:42:38.805Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.ToEntityMetadata[T](EntityMetadata metadata, Boolean includeState)
[2024-05-29T15:42:38.805Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.<GetEntityAsync>b__6_0[TState](EntityMetadata e, Boolean s)
[2024-05-29T15:42:38.805Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.GetEntityCoreAsync[TMetadata](EntityInstanceId id, Boolean includeState, Func`3 select, CancellationToken cancellation)
[2024-05-29T15:42:38.805Z]    at AzureReaper.EventGridTrigger.Run(EventGridEvent eventGridEvent, DurableTaskClient client) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/EventGridTrigger.cs:line 36
[2024-05-29T15:42:38.805Z]    at AzureReaper.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 43
[2024-05-29T15:42:38.806Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-05-29T15:42:38.806Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-05-29T15:42:38.806Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
[2024-05-29T15:42:38.806Z] Stack:    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(Type parentType)
[2024-05-29T15:42:38.806Z]    at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2024-05-29T15:42:38.806Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
[2024-05-29T15:42:38.806Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2024-05-29T15:42:38.806Z]    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
[2024-05-29T15:42:38.806Z]    at System.Text.Json.JsonSerializer.ReadFromSpanAsObject(ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
[2024-05-29T15:42:38.806Z]    at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
[2024-05-29T15:42:38.806Z]    at Azure.Core.Serialization.JsonObjectSerializer.Deserialize(Stream stream, Type returnType, CancellationToken cancellationToken)
[2024-05-29T15:42:38.806Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.ObjectConverterShim.Deserialize(String data, Type targetType) in /_/src/Worker.Extensions.DurableTask/ObjectConverterShim.cs:line 32
[2024-05-29T15:42:38.806Z]    at Microsoft.DurableTask.DataConverter.Deserialize[T](String data)
[2024-05-29T15:42:38.806Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.ToEntityMetadata[T](EntityMetadata metadata, Boolean includeState)
[2024-05-29T15:42:38.806Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.<GetEntityAsync>b__6_0[TState](EntityMetadata e, Boolean s)
[2024-05-29T15:42:38.806Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableEntityClient.GetEntityCoreAsync[TMetadata](EntityInstanceId id, Boolean includeState, Func`3 select, CancellationToken cancellation)
[2024-05-29T15:42:38.806Z]    at AzureReaper.EventGridTrigger.Run(EventGridEvent eventGridEvent, DurableTaskClient client) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/EventGridTrigger.cs:line 36
[2024-05-29T15:42:38.806Z]    at AzureReaper.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in /Users/userprofile/Projects/oss/az-reaper/src/AzureReaper.Functions/Microsoft.Azure.Functions.Worker.Sdk.Generators/Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator/GeneratedFunctionExecutor.g.cs:line 43
[2024-05-29T15:42:38.806Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-05-29T15:42:38.806Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-05-29T15:42:38.806Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.
```

**Comment by lrottach** [comment]
Some more details:
Signaling an entity works if the entity never existed before.
The error happens after signaling an entity the second time.

**Comment by lrottach** [comment]
Issue was caused by the following lines inside the EventGridTrigger's code.
Will be removed as part of this fix. Pre-Validation for existing entities may be added later.

```csharp
// Read entities state to process later
EntityMetadata<AzureResourceEntity>? entityState = await client.Entities.GetEntityAsync<AzureResourceEntity>(entityId);
```
